name: ci

on:
 push:
   branches:
     - main
 pull_request:
   types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      
      - name: Install dependencies
        run: go mod download

      - name: Test and coverage
        run: go test ./... -race -coverprofile=coverage.out -json > report.json

      - name: Go Vet
        run: go vet -json ./... 2> govet-report.out

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}